import { useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { findPublicProfile } from "../data/profileStorage";
import { useTheme } from "../theme/ThemeContext";
import { PublicProfileScreen } from "./PublicProfileScreen";
import type { Profile } from "../types/profile";

export function DiscoverScreen({onClose}:{onClose:()=>void}){
 const {colors}=useTheme(); const [id,setId]=useState(""); const [busy,setBusy]=useState(false); const [profile,setProfile]=useState<Profile|null>(null); const [message,setMessage]=useState("");
 if(profile)return <PublicProfileScreen profile={profile} onClose={()=>setProfile(null)}/>;
 const search=async()=>{if(busy||!id.trim())return;setMessage("");setBusy(true);const p=await findPublicProfile(id);setBusy(false);if(p)setProfile(p);else setMessage("🕵🏻 Ohhh... someone is feeling shy today and gone private!");};
 return <View style={[styles.screen,{backgroundColor:colors.background}]}><TouchableOpacity onPress={onClose}><Text style={[styles.back,{color:colors.accent}]}>‹ Back</Text></TouchableOpacity><Text style={[styles.kicker,{color:colors.accent}]}>DISCOVERY</Text><Text style={[styles.title,{color:colors.text}]}>Find someone.</Text><Text style={[styles.sub,{color:colors.textSecondary}]}>Enter their unique Profile ID to open their public story.</Text><View style={[styles.card,{backgroundColor:colors.surfaceRaised,borderColor:colors.border}]}><Text style={[styles.label,{color:colors.textMuted}]}>PROFILE ID</Text><TextInput value={id} onChangeText={setId} autoCapitalize="characters" placeholder="PF-7K4X92" placeholderTextColor={colors.textMuted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/><TouchableOpacity onPress={search} style={[styles.button,{backgroundColor:colors.accent}]}>{busy?<ActivityIndicator color="#FFF"/>:<Text style={styles.buttonText}>Search profile →</Text>}</TouchableOpacity>{!!message&&<Text style={[styles.message,{color:colors.textSecondary}]}>{message}</Text>}</View><Text style={[styles.note,{color:colors.textMuted}]}>Only profiles marked PUBLIC can be discovered.</Text></View>;
}
const styles=StyleSheet.create({screen:{flex:1,padding:22,paddingTop:45},back:{fontSize:16,fontWeight:"900",marginBottom:35},kicker:{fontSize:10,fontWeight:"900",letterSpacing:2},title:{fontSize:34,fontWeight:"900",marginTop:8},sub:{fontSize:14,lineHeight:21,marginTop:6,marginBottom:22},card:{borderWidth:1,borderRadius:24,padding:18},label:{fontSize:10,fontWeight:"900",letterSpacing:1.5,marginBottom:8},input:{height:56,borderWidth:1,borderRadius:15,paddingHorizontal:16,fontSize:18,fontWeight:"800",letterSpacing:1},button:{height:54,borderRadius:15,alignItems:"center",justifyContent:"center",marginTop:12},buttonText:{color:"#FFF",fontWeight:"900",fontSize:15},message:{textAlign:"center",fontSize:14,lineHeight:21,fontWeight:"700",marginTop:18},note:{textAlign:"center",fontSize:11,marginTop:18}});
