import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useTheme } from "../theme/ThemeContext";
import type { Profile } from "../types/profile";

type DocumentItem={id:string;name:string;type:string;note?:string;visibility:"public"|"private"};
export function DocumentsScreen({profile,onSave,onClose}:{profile:Profile;onSave:(p:Profile)=>void;onClose:()=>void}){
 const {colors}=useTheme(); const docs=profile.documents||[]; const [name,setName]=useState(""); const [type,setType]=useState("Certificate"); const [note,setNote]=useState("");
 const add=()=>{if(!name.trim())return; const next={...profile,documents:[...docs,{id:Date.now().toString(),name:name.trim(),type:type.trim()||"Document",note:note.trim(),visibility:"private" as const}]};onSave(next);setName("");setNote("");Alert.alert("Saved","Document record added. Attachments can be connected when file storage is enabled.");};
 const remove=(id:string)=>onSave({...profile,documents:docs.filter(x=>x.id!==id)});
 return <ScrollView contentContainerStyle={styles.container}><TouchableOpacity onPress={onClose}><Text style={[styles.back,{color:colors.accent}]}>‹ Back</Text></TouchableOpacity><Text style={[styles.eyebrow,{color:colors.accent}]}>DOCUMENTS</Text><Text style={[styles.title,{color:colors.text}]}>Professional records</Text><Text style={[styles.note,{color:colors.textSecondary}]}>Keep a structured index of certificates, resumes, portfolios and other evidence.</Text>
 <View style={[styles.form,{backgroundColor:colors.surfaceRaised,borderColor:colors.border}]}><Field label="Document name" value={name} onChange={setName} colors={colors}/><Field label="Type" value={type} onChange={setType} colors={colors}/><Field label="Note" value={note} onChange={setNote} colors={colors}/><TouchableOpacity onPress={add} style={[styles.button,{backgroundColor:colors.accent}]}><Text style={styles.buttonText}>Add document record</Text></TouchableOpacity></View>
 {docs.map(d=><View key={d.id} style={[styles.card,{backgroundColor:colors.surfaceRaised,borderColor:colors.border}]}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:colors.text}]}>{d.name}</Text><Text style={[styles.meta,{color:colors.textSecondary}]}>{d.type} • {d.visibility}</Text>{!!d.note&&<Text style={[styles.meta,{color:colors.textMuted}]}>{d.note}</Text>}</View><TouchableOpacity onPress={()=>remove(d.id)}><Text style={[styles.delete,{color:colors.warning}]}>Delete</Text></TouchableOpacity></View>)}
 </ScrollView>;
}
function Field({label,value,onChange,colors}:{label:string;value:string;onChange:(v:string)=>void;colors:any}){return <View style={{marginBottom:11}}><Text style={[styles.label,{color:colors.textMuted}]}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={label} placeholderTextColor={colors.textMuted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/></View>}
const styles=StyleSheet.create({container:{padding:22,paddingBottom:50},back:{fontSize:16,fontWeight:"800",marginBottom:18},eyebrow:{fontSize:12,fontWeight:"800",letterSpacing:2},title:{fontSize:28,fontWeight:"900",marginTop:8},note:{fontSize:14,lineHeight:20,marginTop:8,marginBottom:18},form:{borderWidth:1,borderRadius:20,padding:17},label:{fontSize:10,fontWeight:"800",letterSpacing:1,marginBottom:5},input:{height:46,borderWidth:1,borderRadius:12,paddingHorizontal:12,marginBottom:1},button:{height:48,borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:4},buttonText:{color:"#FFF",fontWeight:"800"},card:{borderWidth:1,borderRadius:16,padding:15,marginTop:10,flexDirection:"row",alignItems:"center"},cardTitle:{fontSize:15,fontWeight:"800"},meta:{fontSize:12,marginTop:4},delete:{fontWeight:"800",paddingLeft:10}});
