import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useTheme } from "../theme/ThemeContext";
import type { Profile } from "../types/profile";

type Kind="education"|"employment"|"project"|"skill"|"certification"|"achievement";
export function ManageProfileScreen({profile,onSave,onClose}:{profile:Profile;onSave:(p:Profile)=>void;onClose:()=>void}){
 const {colors}=useTheme(); const [kind,setKind]=useState<Kind>("education"); const [fields,setFields]=useState<Record<string,string>>({});
 const set=(k:string,v:string)=>setFields(x=>({...x,[k]:v}));
 const add=()=>{const id=Date.now().toString(); let next=profile;
 if(kind==="education") next={...profile,education:[...profile.education,{id,institution:fields.institution||"",qualification:fields.qualification||"",field:fields.field,startYear:fields.startYear,endYear:fields.endYear,location:fields.location,visibility:"public"}]};
 if(kind==="employment") next={...profile,employment:[...profile.employment,{id,company:fields.company||"",role:fields.role||"",startDate:fields.startDate||"",endDate:fields.endDate,location:fields.location,current:fields.current==="true",visibility:"public"}]};
 if(kind==="project") next={...profile,projects:[...profile.projects,{id,name:fields.name||"",description:fields.description||"",role:fields.role,status:fields.status,technologies:(fields.technologies||"").split(",").map(x=>x.trim()).filter(Boolean),visibility:"public"}]};
 if(kind==="skill") next={...profile,skills:[...profile.skills,{id,name:fields.name||"",category:fields.category||"General",level:(fields.level||"Intermediate") as any,visibility:"public"}]};
 if(kind==="certification") next={...profile,certifications:[...profile.certifications,{id,name:fields.name||"",issuer:fields.issuer||"",issueDate:fields.issueDate,credentialId:fields.credentialId,visibility:"public"}]};
 if(kind==="achievement") next={...profile,achievements:[...profile.achievements,{id,title:fields.title||"",issuer:fields.issuer,date:fields.date,description:fields.description,visibility:"public"}]};
 onSave(next);setFields({});Alert.alert("Saved",kind.charAt(0).toUpperCase()+kind.slice(1)+" added.");
 };
 const remove=(kind:Kind,id:string)=>{const key=kind==="education"?"education":kind==="employment"?"employment":kind==="project"?"projects":kind==="skill"?"skills":kind==="certification"?"certifications":"achievements";onSave({...profile,[key]:(profile as any)[key].filter((x:any)=>x.id!==id)});};
 const specs:Record<Kind,{label:string;fields:string[]}>={education:{label:"Education",fields:["institution","qualification","field","startYear","endYear","location"]},employment:{label:"Employment",fields:["company","role","startDate","endDate","location","current"]},project:{label:"Project",fields:["name","description","role","status","technologies"]},skill:{label:"Skill",fields:["name","category","level"]},certification:{label:"Certification",fields:["name","issuer","issueDate","credentialId"]},achievement:{label:"Achievement",fields:["title","issuer","date","description"]}};
 const key=kind==="education"?"education":kind==="employment"?"employment":kind==="project"?"projects":kind==="skill"?"skills":kind==="certification"?"certifications":"achievements"; const list=(profile as any)[key]||[];
 return <ScrollView contentContainerStyle={styles.container}><TouchableOpacity onPress={onClose}><Text style={[styles.back,{color:colors.accent}]}>‹ Back</Text></TouchableOpacity><Text style={[styles.eyebrow,{color:colors.accent}]}>PROFILE DATA</Text><Text style={[styles.title,{color:colors.text}]}>Build your professional record</Text>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginVertical:16}}>{(Object.keys(specs) as Kind[]).map(k=><TouchableOpacity key={k} onPress={()=>{setKind(k);setFields({})}} style={[styles.chip,{backgroundColor:k===kind?colors.accentSoft:colors.surface,borderColor:k===kind?colors.accent:colors.border}]}><Text style={{color:k===kind?colors.accent:colors.text,fontWeight:"800"}}>{specs[k].label}</Text></TouchableOpacity>)}</ScrollView>
 <View style={[styles.form,{backgroundColor:colors.surfaceRaised,borderColor:colors.border}]}>{specs[kind].fields.map(f=><View key={f} style={{marginBottom:10}}><Text style={[styles.label,{color:colors.textMuted}]}>{f}</Text><TextInput value={fields[f]||""} onChangeText={v=>set(f,v)} placeholder={f==="technologies"?"React, TypeScript, Node":f} placeholderTextColor={colors.textMuted} multiline={f==="description"} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface},f==="description"&&{height:90,textAlignVertical:"top"}]}/></View>)}<TouchableOpacity onPress={add} style={[styles.button,{backgroundColor:colors.accent}]}><Text style={styles.buttonText}>Add {specs[kind].label}</Text></TouchableOpacity></View>
 {list.map((x:any)=><View key={x.id} style={[styles.item,{backgroundColor:colors.surfaceRaised,borderColor:colors.border}]}><View style={{flex:1}}><Text style={[styles.itemTitle,{color:colors.text}]}>{x.name||x.title||x.role||x.qualification}</Text><Text style={[styles.itemMeta,{color:colors.textSecondary}]}>{x.company||x.institution||x.issuer||x.category||""}</Text></View><TouchableOpacity onPress={()=>remove(kind,x.id)}><Text style={[styles.delete,{color:colors.warning}]}>Delete</Text></TouchableOpacity></View>)}
 </ScrollView>;
}
const styles=StyleSheet.create({container:{padding:22,paddingBottom:50},back:{fontSize:16,fontWeight:"800"},eyebrow:{fontSize:12,fontWeight:"800",letterSpacing:2,marginTop:18},title:{fontSize:28,fontWeight:"900",marginTop:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:99,borderWidth:1,marginRight:8},form:{borderWidth:1,borderRadius:20,padding:17},label:{fontSize:10,fontWeight:"800",letterSpacing:1,marginBottom:5,textTransform:"capitalize"},input:{minHeight:45,borderWidth:1,borderRadius:12,paddingHorizontal:12,fontSize:14},button:{height:48,borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:4},buttonText:{color:"#FFF",fontWeight:"800"},item:{borderWidth:1,borderRadius:16,padding:14,marginTop:9,flexDirection:"row",alignItems:"center"},itemTitle:{fontSize:15,fontWeight:"800"},itemMeta:{fontSize:12,marginTop:4},delete:{fontWeight:"800",paddingLeft:10}});
