import { Alert, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useTheme } from "../theme/ThemeContext";
import { ThemePicker } from "../components/ThemePicker";
import { signOut } from "../data/authStorage";
import type { Profile } from "../types/profile";
export function SettingsScreen({profile,onManage,onDocuments,onPublic,onSignOut,onSave}:{profile:Profile;onManage:()=>void;onDocuments:()=>void;onPublic:()=>void;onSignOut?:()=>void;onSave:(p:Profile)=>void}){
 const {colors}=useTheme(); const share=async()=>{await Share.share({message:profile.fullName+" — "+profile.headline+"\n"+(profile.location||"")+"\n\n"+profile.summary+"\n\nPro-Filio professional profile"});}; const exportCV=async()=>{await Share.share({message:buildCV(profile),title:profile.fullName+" CV"});}; const toggle=()=>{const next={...profile,visibility:profile.visibility==="public"?"private":"public"} as Profile;onSave(next);Alert.alert("Visibility updated","Profile preview is now "+next.visibility+".")}; const logout=async()=>{await signOut();onSignOut?.()};
 return <ScrollView contentContainerStyle={styles.container}><Text style={[styles.eyebrow,{color:colors.accent}]}>CONTROL CENTER</Text><Text style={[styles.title,{color:colors.text}]}>Profile, sharing & settings</Text>
 <Action title="Edit all professional data" description="Education, employment, projects, skills, certifications and achievements" onPress={onManage} colors={colors}/><Action title="Documents & evidence" description={profile.documents.length+" document records"} onPress={onDocuments} colors={colors}/><Action title="Public profile preview" description={profile.visibility==="public"?"Public":"Private preview"} onPress={onPublic} colors={colors}/><Action title="Share profile" description="Share a clean text profile through the device share sheet" onPress={share} colors={colors}/><Action title="Export CV / resume text" description="Generate a structured CV payload ready for PDF tooling" onPress={exportCV} colors={colors}/>
 <Text style={[styles.section,{color:colors.text}]}>Privacy</Text><View style={[styles.privacy,{backgroundColor:colors.surfaceRaised,borderColor:colors.border}]}><Text style={[styles.privacyTitle,{color:colors.text}]}>Profile visibility: {profile.visibility}</Text><Text style={[styles.note,{color:colors.textSecondary}]}>The public preview is available locally. A hosted public URL requires a backend and domain.</Text><TouchableOpacity onPress={toggle}><Text style={[styles.link,{color:colors.accent}]}>Toggle visibility</Text></TouchableOpacity></View>
 <Text style={[styles.section,{color:colors.text}]}>Appearance</Text><ThemePicker/><TouchableOpacity onPress={logout} style={[styles.logout,{borderColor:colors.border}]}><Text style={[styles.logoutText,{color:colors.warning}]}>Sign out on this device</Text></TouchableOpacity><Text style={[styles.footer,{color:colors.textMuted}]}>Pro-Filio • foundation ready for a hosted backend</Text></ScrollView>;
}
function Action({title,description,onPress,colors}:{title:string;description:string;onPress:()=>void;colors:any}){return <TouchableOpacity onPress={onPress} style={[styles.action,{backgroundColor:colors.surfaceRaised,borderColor:colors.border}]}><View style={{flex:1}}><Text style={[styles.actionTitle,{color:colors.text}]}>{title}</Text><Text style={[styles.actionDescription,{color:colors.textMuted}]}>{description}</Text></View><Text style={[styles.chevron,{color:colors.textMuted}]}>›</Text></TouchableOpacity>}
function buildCV(p:Profile){return [p.fullName,p.headline,p.email||"",p.location||"","","SUMMARY",p.summary,"","EXPERIENCE",...p.employment.map(x=>x.role+" | "+x.company+" | "+x.startDate+" - "+(x.current?"Present":x.endDate||"")),"","EDUCATION",...p.education.map(x=>x.qualification+" | "+x.institution),"","PROJECTS",...p.projects.map(x=>x.name+" | "+x.description),"","SKILLS",...p.skills.map(x=>x.name+" ("+(x.level||"")+")"),"","CERTIFICATIONS",...p.certifications.map(x=>x.name+" | "+x.issuer),"","ACHIEVEMENTS",...p.achievements.map(x=>x.title+" | "+(x.issuer||""))].join("\n");}
const styles=StyleSheet.create({container:{padding:22,paddingBottom:50},eyebrow:{fontSize:12,fontWeight:"800",letterSpacing:2},title:{fontSize:28,fontWeight:"900",marginTop:8,marginBottom:20},action:{borderWidth:1,borderRadius:17,padding:16,marginBottom:9,flexDirection:"row",alignItems:"center"},actionTitle:{fontSize:15,fontWeight:"800"},actionDescription:{fontSize:12,lineHeight:17,marginTop:4},chevron:{fontSize:27,paddingLeft:10},section:{fontSize:20,fontWeight:"800",marginTop:25,marginBottom:10},privacy:{borderWidth:1,borderRadius:17,padding:16},privacyTitle:{fontSize:15,fontWeight:"800"},note:{fontSize:12,lineHeight:18,marginTop:6},link:{fontWeight:"800",marginTop:12},logout:{borderWidth:1,borderRadius:14,height:48,alignItems:"center",justifyContent:"center",marginTop:24},logoutText:{fontWeight:"800"},footer:{fontSize:11,textAlign:"center",marginTop:24}});
