export type ThemeName = "softExecutive"|"lavenderGlass"|"mintGlass"|"roseQuartz"|"midnight"|"obsidian"|"titanium"|"paper";
export type ThemeColors={background:string;surface:string;surfaceRaised:string;border:string;text:string;textSecondary:string;textMuted:string;accent:string;accentSoft:string;success:string;warning:string;track:string;profile:string;education:string;career:string;projects:string;achievements:string;certifications:string;documents:string;neutral:string};
export type ThemeDefinition={name:ThemeName;label:string;description:string;colors:ThemeColors};
const category={profile:"#8A84F5",education:"#6C9AF5",career:"#4BC79F",projects:"#A17AF0",achievements:"#E6AF4B",certifications:"#D982AD",documents:"#E48A4A",neutral:"#8993A3"};
export const themes:ThemeDefinition[]=[
{name:"obsidian",label:"Obsidian",description:"Cinematic black with restrained lavender highlights.",colors:{background:"#080A0D",surface:"#101318",surfaceRaised:"#171B22",border:"#2A3039",text:"#F5F7FA",textSecondary:"#AEB6C2",textMuted:"#737D8B",accent:"#9A93FF",accentSoft:"#29294A",success:"#4BC79F",warning:"#E6AF4B",track:"#292E37",...category}},
{name:"midnight",label:"Midnight",description:"Deep blue with a cinematic professional finish.",colors:{background:"#0A1020",surface:"#111A2C",surfaceRaised:"#18233A",border:"#293752",text:"#F4F7FC",textSecondary:"#AAB6CB",textMuted:"#7D899F",accent:"#9B95FF",accentSoft:"#2B2B55",success:"#4BC79F",warning:"#E6AF4B",track:"#27334A",...category}},
{name:"titanium",label:"Titanium",description:"Cool metallic monochrome.",colors:{background:"#111416",surface:"#191D20",surfaceRaised:"#202529",border:"#30363C",text:"#F3F5F6",textSecondary:"#B7BEC5",textMuted:"#858D95",accent:"#CDD4DC",accentSoft:"#343A40",success:"#68B49B",warning:"#D6AA5D",track:"#30363C",...category}},
{name:"softExecutive",label:"Soft Executive",description:"Clean light professional surfaces.",colors:{background:"#EEF2F8",surface:"#F7F9FD",surfaceRaised:"#FFFFFF",border:"#D4DCE8",text:"#172033",textSecondary:"#667085",textMuted:"#818A9A",accent:"#6D6AEF",accentSoft:"#E4E5FF",success:"#37B987",warning:"#E8A93A",track:"#DDE2EC",...category}},
{name:"lavenderGlass",label:"Lavender Glass",description:"Bright violet glass surfaces.",colors:{background:"#F0EEFA",surface:"#F8F6FF",surfaceRaised:"#FFFFFF",border:"#DDD5F1",text:"#25203A",textSecondary:"#716A86",textMuted:"#9189A5",accent:"#8068E8",accentSoft:"#E9E1FF",success:"#3BBF9B",warning:"#E3A93D",track:"#E2DDF0",...category}},
{name:"mintGlass",label:"Mint Glass",description:"Fresh green glass.",colors:{background:"#EDF5F3",surface:"#F6FBFA",surfaceRaised:"#FFFFFF",border:"#D2E3DF",text:"#172B2A",textSecondary:"#607673",textMuted:"#80928F",accent:"#38AE91",accentSoft:"#DDF3EC",success:"#2DAE78",warning:"#D99B38",track:"#D9E8E4",...category}},
{name:"roseQuartz",label:"Rose Quartz",description:"Soft editorial blush.",colors:{background:"#F7F0F4",surface:"#FCF7FA",surfaceRaised:"#FFFFFF",border:"#E8D7E0",text:"#30212B",textSecondary:"#76636D",textMuted:"#99858F",accent:"#D477A0",accentSoft:"#F6DCE8",success:"#4AAE8A",warning:"#D79A3D",track:"#E9DDE4",...category}},
{name:"paper",label:"Paper",description:"Editorial paper.",colors:{background:"#F3F0E9",surface:"#FAF8F2",surfaceRaised:"#FFFEFA",border:"#DED8CB",text:"#25231F",textSecondary:"#6E6A61",textMuted:"#8D887D",accent:"#5E6B9A",accentSoft:"#E4E7F1",success:"#4C9276",warning:"#B9873F",track:"#DED9CE",...category}}
];
export const defaultTheme:ThemeName="obsidian";
export const getTheme=(name:ThemeName)=>themes.find(theme=>theme.name===name)??themes[0];
